### ISSUE TITLE
Use LZ4 def Zram Compression.

### ISSUE THREAD

**Issue by Ravi-Kishor** [vlxlxlv/android-kernel-common-5.10#1]
LZ4 is perfect balance between speed and compression ratio & is def on almost all mainstream Distros (even Arch Wiki recommends it). So switching back to LZ4 would be great for mobile devices having to decrease cpu overhead and improve  some battery backup.

Also don't experiment  weird things like Zram-Swappiness to 10. It should be 60, everywhere its recommended. Lowering this won't be beneficial unless many fine tuning is done device specific in both device tree and kernel side.

**Comment by vlxlxlv** [comment]
okay, thx for suggestion. i'll apply that on next update

**Comment by Ravi-Kishor** [comment]
Great, glad to hear that.
